<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="ViewAllMovies.aspx.cs" Inherits="FirstWebForm.ViewAllMovies" %>

<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <h1 >Movie List</h1>

    <asp:GridView ID="GridView1" runat="server"
        AutoGenerateColumns="False"
        AutoGenerateDeleteButton="True"
        AutoGenerateEditButton="True"
        DataKeyNames="MovieId"
        CssClass="mygrdContent"
        PagerStyle-CssClass="pager"
        HeaderStyle-CssClass="header"
        OnRowDeleting="GridView1_RowDeleting"
        OnRowUpdating="OnRowUpdating"
        OnRowEditing="OnRowEditing"
        OnRowCancelingEdit="OnRowCancelingEdit" CellPadding="4" ForeColor="Black" GridLines="None" HorizontalAlign="Center" OnSelectedIndexChanged="GridView1_SelectedIndexChanged" Width="80%">

        <AlternatingRowStyle BackColor="White" ForeColor="#284775" />

        <Columns>
            <asp:TemplateField HeaderText="Movie Name">
                <ItemTemplate>
                    <asp:Label ID="lblMovieName" runat="server" Text='<%# Eval("MovieName") %>'></asp:Label>
                </ItemTemplate>
                <EditItemTemplate>
                    <asp:TextBox ID="txtMovieName" runat="server" Text='<%# Eval("MovieName") %>' Width="140"></asp:TextBox>
                    <asp:RequiredFieldValidator ID="MovieNameRequired" ForeColor="Red"
                        ControlToValidate="txtMovieName" runat="server"
                        ErrorMessage="Please Enter Movie Name">
                    </asp:RequiredFieldValidator>
                </EditItemTemplate>
            </asp:TemplateField>


            <asp:TemplateField HeaderText="Category">
                <ItemTemplate>
                    <asp:Label ID="lblCategory" runat="server" Text='<%# Eval("Category") %>'></asp:Label>
                </ItemTemplate>
                <EditItemTemplate>
                    <asp:TextBox ID="txtCategory" runat="server" Text='<%# Eval("Category") %>' Width="140"></asp:TextBox>
                       <asp:RequiredFieldValidator ID="CategoryRequired" ForeColor="Red"
                        ControlToValidate="txtCategory" runat="server"
                        ErrorMessage="Please Enter Category">
                    </asp:RequiredFieldValidator>
                </EditItemTemplate>
            </asp:TemplateField>


            <asp:TemplateField HeaderText="Rating">
                <ItemTemplate>
                    <asp:Label ID="lblRating" runat="server" Text='<%# Eval("Rating") %>'></asp:Label>
                </ItemTemplate>
                <EditItemTemplate>
                    <asp:TextBox ID="txtRating" runat="server" Text='<%# Eval("Rating") %>' Width="140"></asp:TextBox>
                    <asp:RequiredFieldValidator ID="RatingRequired" ForeColor="Red"
                        ControlToValidate="txtRating" runat="server"
                        ErrorMessage="Please Enter Rating">
                    </asp:RequiredFieldValidator>
                      <asp:RangeValidator ID="RangeValidatorRating" runat="server" ControlToValidate="txtRating"
            ErrorMessage="Enter value in  range 1 to 10" ForeColor="Red" MaximumValue="10" MinimumValue="1"
            SetFocusOnError="True" Type=" Integer" ></asp:RangeValidator>
                </EditItemTemplate>
            </asp:TemplateField>

        </Columns>
    
        <EditRowStyle ForeColor="Black" />

<HeaderStyle CssClass="header"></HeaderStyle>

<PagerStyle CssClass="pager"></PagerStyle>
        <SelectedRowStyle ForeColor="Black" />
    
    </asp:GridView>
    <div>
        <asp:Label runat="server" ID="labelSuccessDeleteMessage" CssClass="bg-danger" ForeColor="Red"></asp:Label>
        <br />
        <asp:Label ID="UpdateSuccess" runat="server"></asp:Label>
    </div>


    <!-- New Grid Using Data Table -->
    <div>
        <h1 class="display-4 text-info ">Movie List</h1>
        <input type="button" class="btn btn-primary" value="Add Movie"/>
        <br />
        <br />
   <table id="example" class="table table-striped table-bordered" style="width:100%">
        <thead>
            <tr>
                <th>Movie Id</th>
                <th>Movie Name</th> 
                <th>Category</th>
                <th>Rating</th> 
            </tr>
        </thead>
        <tbody>
            
        <tfoot>
        </tfoot>
            </table>
        </div> 
<script>
    $(document).ready(function () {
        $.ajax({
            url: 'MovieService.asmx/GetMovies',
            method: 'post',
            dataType: 'json',
            success: function (data) {
                $('#example').DataTable({
                    data: data,
                    columns: [
                        { data: "MovieId" },
                        { data: "MovieName" },
                        { data: "Category" },
                        { data: "Rating" },
                    ]
                });
            }
        });

    });
  
</script>
</asp:Content>
