<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true"
    CodeBehind="ViewAllMovies.aspx.cs" Inherits="FirstWebForm.ViewAllMovies" %>

<%@ Register Assembly="AjaxControlToolkit" Namespace="AjaxControlToolkit" TagPrefix="asp" %>

<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">

 <!--<asp:GridView ID="GridView1" runat="server"
        AutoGenerateColumns="False"
        AutoGenerateDeleteButton="True"
        AutoGenerateEditButton="True"
        DataKeyNames="MovieId"
        CssClass="mygrdContent"
        PagerStyle-CssClass="pager"
        HeaderStyle-CssClass="header"
        OnRowDeleting="GridView1_RowDeleting"
        OnRowUpdating="OnRowUpdating"
        OnRowEditing="OnRowEditing"
        OnRowCancelingEdit="OnRowCancelingEdit" CellPadding="4" ForeColor="Black" GridLines="None" HorizontalAlign="Center" OnSelectedIndexChanged="GridView1_SelectedIndexChanged" Width="80%">

        <AlternatingRowStyle BackColor="White" ForeColor="#284775" />

        <Columns>
            <asp:TemplateField HeaderText="Movie Name">
                <ItemTemplate>
                    <asp:Label ID="lblMovieName" runat="server" Text='<%# Eval("MovieName") %>'></asp:Label>
                </ItemTemplate>
                <EditItemTemplate>
                    <asp:TextBox ID="txtMovieName" runat="server" Text='<%# Eval("MovieName") %>' Width="140"></asp:TextBox>
                    <asp:RequiredFieldValidator ID="MovieNameRequired" ForeColor="Red"
                        ControlToValidate="txtMovieName" runat="server"
                        ErrorMessage="Please Enter Movie Name">
                    </asp:RequiredFieldValidator>
                </EditItemTemplate>
            </asp:TemplateField>


            <asp:TemplateField HeaderText="Category">
                <ItemTemplate>
                    <asp:Label ID="lblCategory" runat="server" Text='<%# Eval("Category") %>'></asp:Label>
                </ItemTemplate>
                <EditItemTemplate>
                    <asp:TextBox ID="txtCategory" runat="server" Text='<%# Eval("Category") %>' Width="140"></asp:TextBox>
                       <asp:RequiredFieldValidator ID="CategoryRequired" ForeColor="Red"
                        ControlToValidate="txtCategory" runat="server"
                        ErrorMessage="Please Enter Category">
                    </asp:RequiredFieldValidator>
                </EditItemTemplate>
            </asp:TemplateField>


            <asp:TemplateField HeaderText="Rating">
                <ItemTemplate>
                    <asp:Label ID="lblRating" runat="server" Text='<%# Eval("Rating") %>'></asp:Label>
                </ItemTemplate>
                <EditItemTemplate>
                    <asp:TextBox ID="txtRating" runat="server" Text='<%# Eval("Rating") %>' Width="140"></asp:TextBox>
                    <asp:RequiredFieldValidator ID="RatingRequired" ForeColor="Red"
                        ControlToValidate="txtRating" runat="server"
                        ErrorMessage="Please Enter Rating">
                    </asp:RequiredFieldValidator>
                      <asp:RangeValidator ID="RangeValidatorRating" runat="server" ControlToValidate="txtRating"
            ErrorMessage="Enter value in  range 1 to 10" ForeColor="Red" MaximumValue="10" MinimumValue="1"
            SetFocusOnError="True" Type=" Integer" ></asp:RangeValidator>
                </EditItemTemplate>
            </asp:TemplateField>

        </Columns>
    
        <EditRowStyle ForeColor="Black" />

<HeaderStyle CssClass="header"></HeaderStyle>

<PagerStyle CssClass="pager"></PagerStyle>
        <SelectedRowStyle ForeColor="Black" />
    
    </asp:GridView>
    <div>
        <asp:Label runat="server" ID="labelSuccessDeleteMessage" CssClass="bg-danger" ForeColor="Red"></asp:Label>
        <br />
        <asp:Label ID="UpdateSuccess" runat="server"></asp:Label>
    </div>
    -->
    <!-- New Grid Using Data Table -->

    <div>
        <link href="Content/GridStyle.css" rel="stylesheet" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <link rel="stylesheet" href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css" />
        <div>
            <h1 class="display-4 text-info ">Movie List</h1>
            <a class="btn btn-primary" id="AddMoviebtn" href="AddMovieForm.aspx" runat="server" >Add Movie</a><br />
          
        </div>
         <!--    <asp:ModalPopupExtender ID="ModalPopupExtender1" runat="server"
                CancelControlID="Button1" PopupControlID="Panel1"
                TargetControlID="AddMoviebtn" BackgroundCssClass="modalBackground">
            </asp:ModalPopupExtender>

            &nbsp;<asp:ToolkitScriptManager ID="ToolkitScriptManager1" runat="server" EnablePageMethods="true">
            </asp:ToolkitScriptManager>

            <asp:Panel ID="panel1" BackColor="White" runat="server" Height="430px" Width="300px" >
              <iframe runat="server" src="AddMovie1.aspx" height="430px" width="300px">
              </iframe>
                <asp:Button ID="Button1" runat="server" class="btn btn-danger text-center" Text="Cancel" />         x
    
            </asp:Panel> -->
    </div>
    <br />
    <br />
    <table id="example" class="table table-striped table-bordered" style="width: 100%">
        <thead>
            <tr>
                <th>Movie Name</th>
                <th>Category</th>
                <th>Rating</th>
                <th>Edit</th>
                <th>Delete</th>
            </tr>
        </thead>
        <tbody>
        <tfoot>
        </tfoot>
    </table>

    <script>
        var editor;
        $(document).ready(function () {
            $.ajax({
                url: 'MovieService.asmx/GetMovies',
                method: 'post',
                dataType: 'json',
                success: function (data) {
                    $('#example').DataTable({
                        data: data,
                        "columnDefs": [
                            { "className": "dt-center", "targets": "_all" }
                        ],
                        columns: [
                            { data: "MovieName" },
                            { data: "Category" },
                            { data: "Rating" },
                            {
                                data: "MovieId", "width": "50px", "render": function (data) {
                                    return '<a class="btn btn-primary"  href="EditMovie1?id=' + data + '" > <i class="fa fa-edit"></i></a>'
                                }
                                },
                                {
                                    data: "MovieId", "width": "50px", "render": function (data) {
                                        return '<a class="btn btn-danger" href="Delete?id=' + data + '" > <i class="fa fa-trash"></i></a>'
                                    }
                            
                            }
                        ],

                        "paging": "full_numbers"
                    });
                }
            });
        });

    </script>

</asp:Content>
 